export enum ApiEnum {
    Customer =  'http://localhost:5194/api/Customer/',
    Report =    'http://localhost:5195/api/Report/',
    DashBoard = 'http://localhost:5195/api/DashBoard/',
    Booking =   'http://localhost:5196/api/Booking/',
    Security =  'http://localhost:5197/api/Security/',
    User =      'http://localhost:5197/api/User/',
    Role =      'http://localhost:5197/api/Role/',
    Module =    'http://localhost:5197/api/Module/',
    Company =   'http://localhost:5198/api/Company/',
    Browser =   'http://localhost:5199/api/Browser/',  
    Select =    'http://localhost:5199/api/Select/',
    HoliDay =   'http://localhost:5199/api/HoliDay/',
    Court =     'http://localhost:5199/api/Court/',    
}