name: Build and Deploy Microfrontends to Azure Static Web App

on:
  push:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build all microfrontends
        run: |
          npm run build-all-qa

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"  # Si todos los microfrontends están en el directorio raíz
          output_location: "dist"  # Aquí apunta a la carpeta de salida, en este caso 'dist'
